apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "dummy.fullname" . }}-store-password
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  password: {{ randAlphaNum 20 | b64enc | quote }}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "dummy.fullname" . }}-certificate
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  secretName: {{ template "dummy.fullname" . }}-tls-secret
  duration: {{ .Values.tls.certificate.duration }}
  renewBefore: {{ .Values.tls.certificate.renewBefore }}
  commonName: {{ .Release.Name }}.{{ .Release.Namespace }}
  dnsNames:
    # Pod DNS name
    - "localhost"
    - "*.{{ .Release.Namespace }}.pod"
    {{- if .Values.global.kubernetes.clusterDomain }}
    - "*.{{ .Release.Namespace }}.pod.{{ .Values.global.kubernetes.clusterDomain }}"
      {{- end }}
      {{- if .Values.tls.certificate.dnsNames }}
      # Additionally declared DNS names
    {{- range .Values.tls.certificate.dnsNames }}
    - "{{ . }}"
    {{- end }}
    {{- end }}
    # The service name, for when accessed through service
    {{- if .Values.global.kubernetes.clusterDomain }}
  {{- end }}
  {{- if .Values.tls.certificate.ipAddresses }}
  ipAddresses:
    # Additionally declared IP addresses
    {{- range .Values.tls.certificate.ipAddresses }}
    - "{{ . }}"
  {{- end }}
  {{- end }}
  subject:
    organizations:
      - Openet
  privateKey:
    rotationPolicy: Always
  keystores:
    jks:
      create: true
      passwordSecretRef:
        name: {{ template "dummy.fullname" . }}-store-password
        key: password
  issuerRef:
    name: {{ .Values.tls.certificate.issuer }}
    kind: ClusterIssuer
    group: cert-manager.io
