apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "chart.fullname" . }}-tls-secret
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-delete-policy": "before-hook-creation, hook-succeeded"
data:
